apiVersion: v1
kind: Service
metadata:
  name: local-cloud-tasks-loadbalancer
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8123
      name: "8123"
      protocol: TCP
      targetPort: 8123
  selector:
    deployment: local-cloud-tasks
  sessionAffinity: None
  type: LoadBalancer
