apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: local-mongo
  name: local-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: local-mongo
  strategy: {}
  template:
    metadata:
      labels:
        deployment: local-mongo
    spec:
      containers:
        - name: local-mongo
          image: mongo:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_DB_URI
              value: mongodb://localhost:27017
            - name: MONGO_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - bash
            - -c
            - >
              mongod --replSet local-mongo-set --port 27017 --bind_ip 127.0.0.1,localhost,$MONGO_POD_IP
            # - while true; do sleep 2; df -h; done
          ports:
            - containerPort: 27017
          resources: {}
          lifecycle:
            postStart:
              exec:
                command: 
                  - bash
                  - -c
                  - >
                    sleep 10 &&
                    config="rs.initiate({_id:\"local-mongo-set\", members:[{_id: 0, host: \"${MONGO_POD_IP}:27017\", priority: 1}]});"; mongosh --host $MONGO_POD_IP:27017 --eval "$config"
      restartPolicy: Always
status: {}
