apiVersion: v1
kind: Service
metadata:
  name: local-mongo-loadbalancer
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 27017
      name: "27017"
      protocol: TCP
      targetPort: 27017
  selector:
    deployment: local-mongo
  sessionAffinity: None
  type: LoadBalancer
